apiVersion: v1
appVersion: 3.20.1-01
deprecated: true
description: DEPRECATED - Sonatype Nexus is an open source repository manager
home: https://www.sonatype.com/nexus-repository-oss
icon: http://www.sonatype.org/nexus/content/uploads/2015/06/Nexus-Logo.jpg
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
name: sonatype-nexus
sources:
- https://github.com/sonatype/nexus-public
- https://github.com/travelaudience/docker-nexus
- https://github.com/travelaudience/kubernetes-nexus
- https://github.com/travelaudience/docker-nexus-backup
version: 1.23.1
